---
title: "当我们谈记账时，我们真正想解决什么"
date: ""
description: "记账为什么总是坚持不下来？"
categories: []
---

几年前我使用Beancount来记录自己的消费情况。

当时践行规矩是：每天晚上抽出一小段时间，记录自己的当天消费活动。

起初这种方法很奏效。我乐在其中，也坚持了挺长一段时间，以为找到了一个绝佳的「坚持记录」的好法子。就把几条经验心得整理[发表在Beancount杂志](https://quaily.com/beancount-magazine)上。可惜我完全忽视了日常活动的多变性也高估了自己对beancount这个工具的掌握程度。开始的时候，我仍然坚持按照原先的简单规则每天记录。从记录消费活动扩展到到记录投资活动，再扩展到观察资产分布和资产情况，商品的种类越来越多，货币的种类越来越多，账本中开设的账户也越来越多...这项活动开始变的耗时，最终成为一种负担，简单的规则不再适用复杂的活动行为。

当初是什么原因开始想要记账？是因为自己发现，虽然工作了几年，但是却没存下什么钱。而女朋友的工资并不比我高，却已经有了非常可观的一笔存款。我无法回答：「我的钱都去哪里了？」这个问题。

随着消费习惯的改善，现在这个问题的答案从原来的Fava^[Beancount账本的可视化程序]报表中转换到了每期的主信用卡账单中。随之而来的另一个问题是：「我现在有多少钱？」因为我发现，有意无意的，钱被我以各种形式分散在了各个银行，股票市场和交易所中，很难直观的对自己目前的资产情况有明确的认识。

为了得到答案，我还是选择了记账这个办法，但是这次我的目的变了，记账的过程，方法和工具也跟着变了。回顾之前的经历，对记账这件事也有了一种新的思考。

# 我们想要是报表，不是记账

不论是「我的钱都去哪里了」还是「我现在有多少钱」，我最终想要看到都只是记账后由这些数据生成的汇总报表。生成报表的数据越精细，粒度越小，报表展示的层次会越丰富。拿「我的钱都去哪里了」为例，每一笔交易可以通过不同分类或者打上[标签](https://quaily.com/beancount-magazine/p/tags-and-examples)，在报表里我看到的信息就可以是：

- 每个周期的总消费
- 周期内通勤总费用
- 周期内一日三餐的总费用
- 周期内的旅行费用，甚至某次旅行的总费用
- ...

记录账单的细节越多，能从数据中得到的信息也越多。这类明细账，是我们通常认为的记账。账单记录的越清楚，细节越多，意味着投如记账的工时就越多，会更辛苦。

相反，如果得到每个月的总消费已经够了，那我完全可以依赖每个月的信用卡账单来达到目的，可以做到不记账。

**我们需要数据告诉我们什么，决定了我们收集什么数据以及如何收集数据。** 例如：

|目的|记账方法|
|---|---|
|我的钱都花到哪里去了？|明细消费流水|
|我有多少钱/资产/资产配置怎么分配的？|资产快照（投资账户，活期账户）|
|我的投资回报怎么样？|记录加减仓明细（需要持仓成本才能计算^[这里讨论单个投资标的，如果只想观察整体的情况亦可以使用快照的方式]）|

不同的记账方式，要求我们花费的精力也有所不同。总的来说，我认为记账方式大致可以分为两类：

1. 记录明细账单（明细法）
2. 记录资产余额（快照法）

明细法要求我们付出更多的时间，花费更多的精力，比较辛苦。快照法则只关心最账户「顶层」的数字，并不需要了解账户间的往来，比较轻松。我也在用这种方法回答「我现在还有多少钱」这个问题。

如果我用明细法去回答「我有多少钱？」的问题，虽然最终也能得到答案，但这样的时间投入和产出相比，非常不划算，而且更容易产生疲惫和无所得感。

# 为什么坚持记账总是失败

记账的产物是报表。不同报表需求，对应的数据口径不同；口径不同，方法不同；方法不同，投入也不同。

记账难以坚持，根源在于两件事情相互作用：

1. 需求不清晰：错误的把记账过程或者工具当作重点，而忽略了自己想从账本中得到什么结果。
2. 工具不匹配：用复杂的工具解决简单的问题，或者用简单的工作却想要做精细的分析。

# 复杂的工具意味着更高的学习成本

Beancount是一个非常灵活的工具，它可以回答「我的钱都去哪里了」亦可以回答「我现在还有多少钱」但它同时也是复杂的。

我使用GoogleSheet只花了一点时间就对「我现在有多少钱」有一个大概的认识，使用Beancount可能要花不止2倍的时间，因为相比之前的账本又多出了很多新的账户和资产种类。

每一个记账软件的背后都隐藏着作者想要解决的某个（某些）问题，
