---
title: "请认真对待自己的钱"
date: "2026-01-19 11:58"
categories: ['money']
---

和以前的同事一起吃饭，意外得知他自己现在欠着大约十几万的消费贷款。老家有两个在上学的孩子，每个月不仅有6000多的房贷要还，还要还消费贷的钱。听的我有点喘不过气，问他借钱都用来干什么了，才发现他做的一些事情和我刚毕业工作那会儿的消费行为如出一辙：不把钱当钱态度加上对未来过度盲目的乐观，直到还钱成了生活的主线任务...

# 我对钱错误的认知和消费观

我想讲两件事来描述当时的自己对花钱的心态，一个发生在刚毕业的时候，另一个发生在工作半年后。

大学后半段的时候，第一次接触健身，那时候自己什么都不懂，也不会用里面的器材，偶尔请教健身房里的教练。一来二去熟络起来了，就报了一个月的私教课跟着他练。教练是蒙古族，后面没多久就决定回蒙古去了。这一个月里，每周要去3~4次，刚开始要我每次训练完吃12个鸡蛋，我实在是吃不下，每次就只吃6个。我从一个引体向上都做不了到最后验收的时候能一口气做15个，深蹲也做到了80KG，卧推也有成效，对健身带来的体能和肌肉提升很满意。

毕业开始工作以后就延续了健身的习惯，但是健身卡的价格比学校里贵很多，私教课也是，但觉得是在自己的健康上花钱，就还是用信用卡消费了超过一个月收入的价钱办了年卡，买了课，用分期的方式还款。

这期间还在教练的建议下，买了他推荐的蛋白粉和BCAA（支链氨基酸），后来课程又从增肌升级成了康复+增肌，价格也理所当然的升级了。现在回忆起来，当时的负债总金额可能有3~4倍的月收入了，但当时却一点也没觉得有压力，有负担。一方面，分期金额可能占当时月收入的$\frac{1}{8}$或者$\frac{1}{6}$的样子，觉得每个月自己还能有盈余，无所谓。另一方面，可能是因为几乎不怎么接触过现金，所有的收入和消费都只是屏幕上的数字增减，感知上十万块钱以下都没觉得是很多钱。

这种消费态度又染上了购买最新电子产品的恶习：新出的iPhone，AirPods/AirPods Pro，iPad从mini到Pro，甚至MacBookPro（带TouchBar）都要过一遍瘾^[HomePod得益于停产，出二手没亏钱]，这些每一件单品在24期免息的加持下，显示的月还款金额自己都觉得完全可以接受，即使京东上价格便宜几百块，我还是会选择在Apple Store的官方店铺购买，我对24期免息分期产生了依赖。就这样渐渐地，每个月的还款总金额逐渐逼近月收入的$\frac{1}{2}$。每个月的税后收入，一半用来还信用卡，剩下一大半几乎全部交了房租。日子越来越紧巴，就想办法拆东墙补西墙，开始从银行借小额的贷款，5000，8000，2,000，3,5000...

这样的日子持续了大半年，可能是银行的信用卡部门洞察到了我的窘迫，第二件事情发生了：一通电话打过来说有一笔优惠利率的80,000的现金提供，每个月利息只需要几百块。我一琢磨每个月有好几笔分期要还，不如拿这个钱一次性把信用卡还了，然后就还这一笔钱就行了，于是就答应了，这是第一次借这么一大笔钱。这下好了，信用卡欠款还完，又觉得自己有钱了，过年回家开始给爸妈也换了新iPhone，带他们去逛街买他们平时自己舍不得买的衣服裤子鞋，化装品什么的，我不把自己的钱当钱，更不把借来的钱当钱。这些经历让也我在几乎毕业后几年没存下什么钱，你问我赚的钱都去哪里了，我自己也说不清楚。

后来花了相当长的时间，改变了消费习惯，才补上了前捅的大窟窿。

# 新的认知

在很长一段时间里，我对两句话深信不疑：

1. 钱买不来幸福，买不来快乐
2. 钱是赚出来的，不是省出来的^[当时觉得自己的工资会年年涨，一年比一年高]

它们构成了我对钱最早的理解，但是现在，我的经历告诉我：

第一句话，像马云说他不喜欢钱一样，建立在已经拥有（过）的前提下也许是成立的，先有才能无。

第二句话，节省自己兜儿里钱的难度要远远小于赚别人口袋里的钱的难度，省钱比赚钱容易实现的多的多。


# 作为警示
我之所以听了同事的话很惊讶，一方面是因为他就像几年前的我一样，本来是他跟着我还有另一个同事，我们三个一起去健身。后来他自己买了很多很多节私教课，买补给（大概率也是教练的推荐）现在才知道花在这上面的钱很多是从银行借来的，另外他还在网上买了很多很多的付费课程，说是想提升自己的竞争力，免得被淘汰，但后来也没坚持学几门。另一方面他还年长我五六岁，竟然和我几年前前犯了几乎一模一样的错误。现在成了自由职业，有家庭有小孩，每个月房贷加消费贷这么多钱要还，仔细想想这样的日子真的很难受。

这其实也是为什么写这篇文章的原因，这个错误我犯过，年长于我的人也不能避免，那其他更年轻的朋友们呢？希望我犯的错误能警示正看到这里的你，请照顾好自己赚得每一分钱，不要迷信开源大于节流，节流是自己能完全控制的最简单的事情。



