---
title: About
date: 1995-09
description: 关于这个网站，内容和作者
categories: []
date-modified: last-modified

---

# About this site

网站名称用Garden这个词，源于对「[数字花园](https://maggieappleton.com/garden-history/)」概念的理解。

- 一个完全自我控制的网络空间，像一个花园一样，随意地生长;
    - 完全由自己控制，意味着花园的样式，种植的种类，都不设限制，完全有自己的主观意识决定；
- 空间中的内容是用心栽培的，随时养护;
- 花园开放且自由，允许在互联网上的任何人游览;

> [Show Your Work](https://book.douban.com/subject/26357206/)这本书也给了我不少动力

网站托管在Github，因为受到yihong的启发：[People Die, but Long Live GitHub](https://github.com/yihong0618/gitblog/issues/177#issue-682267456)

使用[Quarto](https://quarto.org/)制作。当时由于工作需要，需要撰写一些总结报告，报告需要插入用数据生成的图表，Quarto非常适合这项工作，顺便也就给自己用了。

色彩取自我非常喜欢阅读的博客[Entropic Thoughts](https://entropicthoughts.com/index)，第一次发现时，就觉得阅读体验很舒适。

# About the content 

正因是在花园中创作，在属于自己的网络空间中，内容素材不会专注于某一主题或话题，同时也不一定会完整/完美。（但是我还是要尽力而为）


所有内容都源于我的生活，工作，兴趣，经历和经验，包含过程中涉及到的一切。

有时候内容会被**标签**标记，标签对内容分类是一个很好的工具，但是我会谨慎使用：在想不到关联之前，就不打。
你可以在[这里](/pages/categories-and-tags.qmd)找到已经存在的标签名称和它的意义。

::: {.callout-note title="推荐链接披露"}
一些内容的链接，包含我的推荐，如果你介意，可以复制链接地址，在地址栏中修改后打开。
:::

在阅读内容时，可能会看到广告，关于站内出现的广告请参考：[Google AdSense说明](/pages/privacy.qmd)

# About the author

内容>作者。

如果你觉得我写的内容对你有帮助，那别忘了经常回来看看。如果还帮不到你，我也希望有一天我们还能再见。

不过这是个人花园，主观意识会占多数，所以有必要交待一下自己的缺点和偏见（经常补充）：

**缺点和偏见**

- 视技术为工具，用来解决或*加速解决*生活的实际问题。
- 不喜欢低质量，缺乏品味(不用心打磨)的内容。
- 喜欢友善，提供有帮助内容的人。


{{< include ../include/telegram_channel.qmd >}}

# Gardens to hang around
有一些其他人精心构造的花园，我必须要分享给你，真的很好逛！

## 亚洲园
- [欧文Owen](https://www.owenyoung.com/) 

  <small>
  沉浸式翻译的作者 Garden Powerd by [Zola](https://www.getzola.org/)
  </small>

- [極客死亡計劃](https://www.geedea.pro) 

  <small>
  有在用心经营和写作的朋友，似乎还是一位学生，很佩服！
  </small>

## 美洲园
- [格温Gwern](https://gwern.net/)
- [jwz](https://www.jwz.org/blog/)

  <small>
  我是在寻找关于数据备份的过程中偶然发现jwz[关于此话题](https://www.jwz.org/doc/backups.html)的内容。
  后来发现jwz是一个互联网OG，你听说过Mozilla吗，他是Mozilla这个合成词的贡献者。
  你可以去他那里逛逛，也许能发现很多有意思的小玩意。
  </small>

  <small>
  记得不要从HackerNews跳转过去访问jwz的网站。
  </small>

  <small>
  一些可能有用的URI：`/blog/` `hacks` `/doc/` `/webcollage/` `/xscreensaver/`
  </small>





