---
title: "比特币定投计划"
date: "2025-08-18 14:23"
categories: ['money']
---

最近时常会思考一个问题：每年生日，如果给自己准备礼物的话，应该准备什么？

小时候总盼望生日的时候会收到惊喜的礼物。可惜的是，在最渴望的年龄却很少过生日，就更别提收过什么礼物了。时间一久，就忘记了过生日兴奋的感觉，对生日礼物也没什么期待的了。

反倒工作以后，爸妈总能想起那天是狼崽子的生日，也总会送上红包礼物。虽然以前没什么收到惊喜礼物的坚实回忆，但还是会问自己：如果准备礼物的话，自己最想要收到什么？

思来想去，每年买一万块的比特币最合自己的心意。

下一步就是确定怎么使用每年的一万块，是一次性买入，还是分批买入？如果是分批买入，频率和金额怎么选。

贝版在[赚钱不用花那么多时间](https://mp.weixin.qq.com/s/-doLDWnmYBs34z59BwMsbQ)里的观点是DCA在长期以来都比波段交易（比如每次价格下跌5%就买入）表现更好。

并且提出了逢低买入（Dip buying）不如定投（DCA）的几个原因：

1. 永远不知道什么时候是底部
2. 当市场的趋势是上涨时，如果仍然坚持等待底部或者回撤在买入，往往会让你错过上涨日。

这两个理由，自己有深刻的体会：

- $GOOGL 自己心里盘算的可接受价格是$150以下，当价格在$148的那天，我就还想再等等，就等到了今天。
- $0268.HK 同样计划在8HKD以下的时候就应该买入，依旧还是懒到错过底部，至今在等待。

同时借着GPT-5的刚推出热乎劲儿和[Plus会员](/posts/chatgpt-plus-monent.qmd)的深度研究功能，我让ChatGPT根据过去五年和十年的比特币价格，对一次性买入和分批（按月，按周，按天）买入策略进行了收益比较。其结论引用了一份关于一次性买入和DCA的比特币的表现[报告](https://nakamotoportfolio.com/static/docs/DCA_Lumpsum.pdf#:~:text=When%20we%20dig%20deeper%20into,monthly%20DCA%20strategies%20drastically%20underperformed)。

报告的结论是：一次性买入（Lump Sum）在比特币的长期投资中表现更好。并且越早分配资金到比特币，无论是选择一次性投资还是选择每日定期定额投资而非每周或每月定期定额投资，长期回报将越好。

对于DCA策略而言，这里的越早，也意味着更高的买入频率。也就是每日买入累计的比特币数量大于每月买入。

从自己的直觉和「经验」上，我也倾向于认为一次性买入会比DCA获得高回报。为了在合适的「底部」买入，首先要求就是对比特币历史的大涨大跌有清晰的认识，并且要有足够的耐心去等待。如果不幸在高点买入，还要有坚定的心态HODL。

[考虑到自己的个性](/posts/investing-and-personality.qmd)和做这件事的目的，最终的选择是--定投。


接下来就是定投工具和频率。中心化交易所（CEX）都提供定投工具。[CoinMarketCap](https://coinmarketcap.com/rankings/exchanges/)和[CoinGecko](https://www.coingecko.com/en/exchanges)都提供关于CEX的排名。

从交易所的App体验来说，我更喜欢Bybit和OKX，Binance说不上是什么问题，反正用起来就是很奇怪，是最不想用的一个。但是Biance的定投功能和前两者有根本性的不同，并且提供一个非常重要的功能。

Bybit的定投功能通过现货[交易机器人](https://www.bybitglobal.com/zh-MY/help-center/article/FAQ-DCA-Bot)实现，OKX的定投功能是也属于现货[交易策略](https://www.okx.com/zh-hans/learn/fixed-investment-strategy)。

现货交易基于订单簿的形式，每次买入有吃单手续费（Taker），像我这种迷你散户都是大众费率，0.1%。

Binance的定投功能集成在了[闪兑](https://www.binance.com/zh-CN/support/faq/detail/5026705ac87942069b1bdcf5a99ffc48)里，属于交易所报价成交的形式。

> 定投价格与币安现货平台的市场价有所不同。所有定投交易均按照闪兑使用条款执行。

虽然闪兑明确说明不收手续费，但是由于兑换价格由交易所报价，也许大概率报的价格已经包含（部分）交易所的成本了吧。不过，最终选择Binance的原因是它能够将理财账户的资金用于定投计划，对我来说是个重要功能。

也就是资金在[理财](/posts/stablecoin-earnings.qmd)的同时能直接扣除买BTC，和支付宝的余额宝直接买ETF类似。OKX虽然也提供交易账户自动赚币的功能，但是[只开放给VIP用户](https://www.okx.com/zh-hans/help/okx-launches-trading-account-auto-earn)。

使用现货策略交易，每次支付0.1%的手续费还是选择闪兑的交易所报价，哪个更划算？自己并没有实际计算过^[实际上自己不太会算..]。总的来说，Binance的闪兑定投最合适。按照1:7的比例，10000RMB大约1428.57USD(C/T)，每日可投入约3.9，取整的话为4。

剩下的就等到生日那天，打开计划，五年之后再回来看看吧。
