---
title: "日版iPhone大陆Apple Store维修记"
date: "2024-11-03"
date-modified: "last-modified"
categories: []
---

在有AC+的情况下, 屏幕费用188, 背板费用188.

没有AC+的话, 屏幕3000+, 背板1000+

如果上午去, 下午就能修好, 拿到手机, 整个过程在3小时之内. 不过有几点比较特别:

1. Beta版维修, 维修时需要先降级成正式版(工程师会替你降级), 因为需要在维修完成后进行测试, Beta版本的测试环境往往没有就绪.
2. 维修风险告知: 维修失败(小概率事件)后, 会提供国行的**官翻**机器赔偿你.


维修过程中都没有要求出示过购买凭据.

以下是我的设备情况, 供参考:

# 备份恢复

备份使用的是iMazing2, 备份的时候iOS版本为18.2(beta版本)

恢复时, 设备也必须先升级到iOS18.2, 才能进行恢复. 

然而拿到维修后的手机时iOS18.1, 并且处于出厂状态, 需要登陆激活. 千万注意登陆激活后, **不要打开失窃防护**

::: {.callout}
执行恢复过程, 需要关闭查找iPhone功能, 打开失窃防护后该功能无法关闭.

并且打开失窃防护后再关闭, 需要等待1小时
:::

用备份恢复后, 有几个地方需要注意:

## eSIM
esim在恢复之前, 虽然能在系统上看到添加的esim, 但是无法显示之前填写的号码, 不过恢复之后就好了.

## 2FA
Microsoft Authenticator 以前通过微软账户成功同步恢复过, 但是这次却不行. 后来发现丢失数据这种情况并非[个例](https://v2ex.com/t/989278?p=2)

自己同时还使用[2FAS](https://2fas.com/)保存了一些重要的二次验证, 可以正常通过iCloud恢复数据. 
这次经历后, Microsoft Authenticator 可以考虑弃用, 或者用来保存一些易恢或不重要账户的二次验证, 比如工作中的二次验证.


# The Bottom Line

总共花费376, 在这之前还在考虑取消AC+的订阅(每月$9.99), 好在自己比较懒, 省了一大笔钱.

从今天起, 买手机壳, 买屏保, 还是好好保护一下, 不然真的坏掉会好麻烦的...



