---
title: 裁员, 是一件残忍的事情吗?
date: '2024-09-08'
categories:
- worklog
description: 没有人比你更关心你的生活

---

和同事们一起吃饭, 聊天时提到一个来公司有很多年的同事, 被裁员了.
让我感到诧异的是, 一起吃饭的一个同事对公司裁员这件事的评价是: "公司很残忍的"

之所以感到惊讶, 是因为我认为公司裁员是再平常不过的一件事, 几乎可以说是一件可以预见的必然事件.

是因为什么, 我们的看法会有如此大的差异呢? 
我无法猜测他的想法, 但是我想我或许可以从我的角度来解释为什么我认为裁员并不是一件残忍的事情.


## 工作, 是同公司合作

公司雇佣员工, 出发点是为了让员工帮助公司完成一些工作. 是用薪水置换员工的时间, 服务, 劳动力或者专业知识.

在这个过程中, 公司和员工之间建立的是一种合作关系. 
你被公司聘用, 是因为公司通过面试过程, 认为你可以完成需要完成的工作. 
你接受公司的聘用, 是因为公司为你支付的薪水在你的接受范围.


## 奉献, 是自己的选择

员工完成公司支付了薪水部分的工作, 是应该的. 除此之外的工作, 是员工的奉献, 是员工的自由.

选择奉献, 可能会给员工带来超额的回报, 比如更快的涨薪, 更快的升职. 但也可能什么都不会发生.
收益和风险总是并存, 期待获取收益而无视风险, 是危险的.

当员工的利益和公司的利益深度绑定时, 奉献所带来的收益往往才会更客观.

因为自己在公司很多年, 就要求公司必须珍稀自己, 是幼稚的.


## 应该怎么做?
没有人比你更关心你的钱, 也没有人比你更关心你的生活.


除了完成公司付你薪水的工作之外, 你可以选择奉献.
当你在奉献时, 请明白你正在攀爬[第几座山](https://book.douban.com/subject/35048531/#:~:text=2023%E5%B9%B4%E5%BA%A6%E6%8A%A5%E5%91%8A-,%E7%AC%AC%E4%BA%8C%E5%BA%A7%E5%B1%B1,-%E4%BD%9C%E8%80%85%3A%20%5B%E7%BE%8E).
明白奉献的收益和风险, 永远不要把奉献当成是一种义务, 因为你总是在追寻一些东西.

公司作为一个追逐利润的组织, 每个选择都在平衡风险和收益. 自己也应如此.