---
title: "劳动合同期满的后续计划"
description: "从2022年中开始，到2025年终结束，这份寿命3年半的劳动合迎来了终结的一天。"
date: "2025-12-30 20:53"
date-modified: 2026-01-12 11:37
tbl-cap-location: bottom
categories: ['first-time']
---
这是自己第一次经历裁员，公司以不再续签的理由结束了雇佣关系。

在2024年的时候，我写过一篇关于裁员的[文章](/posts/is-layoff-a-cruel-thing.qmd)，最后提到的观点是「公司作为一个追逐利润的组织, 每个选择都在平衡风险和收益. 自己也应如此」现在我同样这样认为，所以当知道自己被裁的那一刻，心态是比较轻松从容的。一方面是公司当下的氛围变的越来越割裂，越来越不健康。另一方面自己也已经在为新的人生旅程做最后准备，等尘埃落定的时候再写一篇新文章来分享这段过程。


# 赔偿金

不续约的赔偿是N*月工资。月工资按照被通知不续约的那个月，往前追溯十二个月加上年终奖计算的平均值。

和合同期内被裁不一样的是，这个赔偿金没有免税额，要合并到收入里缴纳个人所得税，好剑。

# 失业金申领

后面先不打算找新工作了，连年缴纳的社保终于能派上用场了（失业保险）。

如果要计划申领失业金，一定要和人事沟通进行社保减员时理由选择「被动离职」，否则无法在申领。

**确定社保何时减员和减员理由**

- 最稳妥的办法：人事在操作了社保减员后，会收到社保局的短信通知，并且会附上相应理由。

- 自查：在支付宝或者微信只能看到是否减员，看不到减员理由。例如：深圳人社公众号->办事->掌上办事->个人参保信息->参保状态，「正常参保」为未减员。

**金额和时长**

目前，深圳的失业金是2268元/月。按照我的缴纳年限，估摸着最少能领半年。小红书上有很多社保年限和可领取月份对应的表格，根据身边朋友的经验来看是不太准的。所以最后还是以申请的结果为准好了。

登记失业，失业金申领的具体过程：[深圳失业保险金线上申请过程](/posts/shenzhen-unemployment-insurance-application-process/)


# 只缴居民医保

我根据自己当前的情况，打算只参与城乡居民医疗基本保险（居民医保）。也就是只缴纳医保，不缴养老。

以灵活就业身份缴纳的医保属于城镇职工基本医疗保险（职工医保）。职工医保比居民医保贵很多，原因除了计费方式和居民医保不一样外，以灵活就业缴纳，你还需需要承担原本公司替你缴纳的部分。而深圳的居民医保，个人费用目前是400多/年。

不过申领失业金期间，社保局会帮缴职工医保，包含个人部分和统筹部分，自己一分钱都不用缴。领取失业金到期后，还会额外帮你多缴纳3个月。也就说可能9个月后我才需要自己缴纳居民社保。

关于职工医保和居民医保的详细区别，推荐柴知道的「医保怎么用最省钱？2023最清晰实用医保指南，适配全国！」影片。

影片最后提到附件：

- [医保补充内容：各地医保报销政策](https://chaiknows.feishu.cn/docx/ZocfdzGSwoTUuhxE9Z1cIs74nbn)
- [医保补充内容：什么是医保报销目录](https://chaiknows.feishu.cn/docx/A3vodoX7ToPuFjx5GPTcOKoUnOf)
- [医保补充内容：医疗保险和生育保险](https://chaiknows.feishu.cn/docx/YQUudLAfUoxzckxGOL3cA62Hnkf)

```{=html}
<iframe
  src="https://player.bilibili.com/player.html?bvid=BV1GW4y1D7Qp&page=1&autoplay=0&danmaku=0"
  style="width: 100%; aspect-ratio: 16 / 9;"
  scrolling="no"
  frameborder="0"
  allowfullscreen>
</iframe>


关于养老金的部分，没有人比你更在乎你的钱。

{{< tweet user=taresky id=1834819117259669526 >}}


# 可能需要警惕的小动作

这是第一次自己遇到劳动合同时长不是完整3年，和同事闲聊时发现有和我一样签约超3年的（大部分），也有签约3年整的。

虽然不清楚公司这样做的缘由和真实意图，不过考虑到每年年底优化的必然性，让公司损失最小化的情况（最少赔偿），显然把合同定在12月31日是最佳选项。

| 入职时间 | 截止2028年底工龄 | 方案B：签约至12月31日<br>（合同自然到期） | 方案A：签约3年整<br>（合同未到期） |
| :--- | :--- | :--- | :--- |
| **上半年入职**<br><small>2025-05-01</small> | 3年+8个月<br>**折算 N=4** | **公司成本：N (4个月)**<br>性质：合同期满终止<br>优势：无需支付代通知金(+1)；公司单方通知即可；年终奖易拒付。 | **公司成本：N+1 (5个月)**<br>性质：协商解除劳动合同<br>劣势：需支付代通知金；必须协商一致，员工拥有拒签权和谈判年终奖的筹码。 |
| **下半年入职**<br><small>2025-09-01</small> | 3年+4个月<br>**折算 N=3.5** | **公司成本：N (3.5个月)**<br>性质：合同期满终止<br>优势：成本最低，且掌握绝对主动权。 | **公司成本：N+1 (4.5个月)**<br>性质：协商解除劳动合同<br>劣势：成本较高，且面临谈判风险。 |

: 上述表格由Gemini整理

如果要签约不是整年的劳动合同，在上半年签约也会比下半年签约好一些。
