---
title: '"银行"低息贷款招数小记'
date: "2025-09-16 20:20"
categories: ['tome-of-xp']
draft: false
---

最近经常能接到自称是某某银行的业务经理，现在有政策，有一笔贷款可以做到很低的利息，并且先息后本。

自己经常用招行，也听说过招联金融，然后跟我说贷款利率能做到年化2.55%。我琢磨最近确实是有「贴息政策」就约着去了解了一下。

总的来说，一通接触下来，跟自己的预期完全不同。

# 名不副实的银行业务经理

约见见面地点的时候，发给我的是一个招行支行的定位点，这里给我的感觉已经是：可信度+1。

实际接待的地点，在支行后面一栋楼，是一栋明显的租赁办公楼，接待处挂的招牌也和招商银行没有 半点关系，是一个完全不搭边的名字。

其实在这之前几天，也实地探访并接触过打着农业银行旗号的所谓业务经理，夸大其词的说招行给你2.55%利率，我这边能给你做到2.4%！有了农业银行的先前的经验，就已经让我对「助贷公司」这个词有些了解，也知道他们实际和真实的银行之前没有什么联系，属于银行将贷款任务外包，给到助贷公司。

而这些自称是某行业务经理，给我打电话的人，充其量就是一个贷款推销员，负责拉客户而已，经理这个Title，十有八九徒有虚名。

因为到了地点之后，实际和你对接业务的完全是另一个人，经理们称之为主任，所有的操作都由这个主任经手。

> 一件很好笑的事情是：当我说：那个经理跟我讲，你们年化利率是2.4%，主任立马反驳道：什么经理，他们都是客服，负责联系客户的。


# 低利率真相

不论是2.4%还是2.55%，都是噱头，实际都做不到。当问到，你们不是说年化是2.4%/2.55%吗？主任们的标准回答是：那些只有央国企单位员工才能办下来。也许你真是央国企员工，可能他们又有另一套说辞搪塞。

助贷公司提供的真实利率不会低于银行公开的最低基准利率^[目前规定是不得低于3%]。加之他们会收取来自银行的提成和客户成功提款后的手续费 ^[据他们说是提款金额的1%左右]。算上这些成本，实际利率并不低。


# 识别真银行经理

招商银行的工作人员告诉我，他们也确实会通过电话联系客户，主动提供贷款支持。也知道上述助贷公司拉客的操作。识别是不是银行内部人员拨打电话，使用招商银行的App搜索对方的全名，如果能识别到，那就证明是银行工作人员拨打。

奇怪的知识又增加了。
