---
title: "为什么要在意国债收益率"
date: "2025-05-18"
description: "收益率高低对我们普通人意味着什么"
categories: []
draft: false
---

我在2023年底之所以尝试[第一次购买美债](./buying-us-bond.qmd)，是受到了当时高利率背景下，一些财经内容的启发和建议 -- 通过美债，锁定一定时期的高利率。作为尝试，选择了2年期进行试验。

随着后来，中国国债收益率和利率持续下降^[现在[中国10年期国债收益率](https://cn.tradingview.com/markets/bonds/yield-curve-all/)为1.67%]，试验基本得到了验证，同时关于债券，尤其是国债(主要是中国国债和美国国债)的话题也经常被讨论。

金融知识是世界运行的规则之一，可惜的是，学校却从不教授。这篇文章将我对国债的一些基本理解做一个整理，希望对你有所帮助。


# 一些历史事实和现实情况

不论喜欢还是不喜欢，当前阶段，有一些事实是我们必须接受的：

1. 美元是世界货币
2. 美债是世界资产定价的基准

## 世界货币

美国通过二战后建立的布雷顿森林体系(1944年7月)，让美元和黄金价值挂钩，固定汇率兑换，配合马歇尔计划（欧洲复兴计划,1947年6月）和一系列其他的“援助计划”使得美元能在世界范围内流通。

尽管后来，美元不能按照黄金价值刚性兑付,美元和黄金价值脱钩(布雷顿森林体系解体)。但是围绕美元进行计价的习惯，一系列金融基础设施的建设和靠时间积累的美元的流动性优势^[流动性好，市场深度够，在交易时就降低了卖不出去的风险]，以及现在大宗商品（能源，粮食）长期使用美元计价，美元现在依然是世界货币。

## 资产定价的锚

以美元结算的资产，意味着国际间贸易，美国输出美元，其他国家输出商品，用绿色的纸币兑换其他国家的商品。中国也是，也让中国积累了很多美元。如果放着不动，随着通货膨胀，这些绿色的纸币会贬值，因此就要把这些美元投资到其他地方去，让它不贬值。接收美元最好的地方，当然也只有美国了。因此就造就了现在美元的一种循环：

美国输出美元，其他国家输出商品。其他国家拿着赚来的美元，又投资到美国去。

那么投资什么资产呢？对于国家来说，把赚来的美元投资到美国去不是为了大幅增值，又同时需要兼顾流动性的需求，以应对不时需要使用美元的情况。以美国政府信用背书的美国国债，就成了几乎唯一的选择，也是现在以出口为导向的国家，持有美国国债数量最多的原因。

债券，国家可以发行，叫国债，企业也可以发行，叫企业债。当国家发行债券向市场借钱的时候，如果给4.5%的利息，对于企业发行4.2%的利息，虽然对企业来说，借钱的成本低，可是对把钱借出去的人，这个利息就不香了。4.5%比4.2%高不说，国家的信用肯定也要高于企业的信用。因此，企业如果想要借到钱，必须提供比国债利率高的企业债。此时，国债利率^[国债利率：为了方便比较，统一叫利率，实际上应该是[收益率](./steps-of-buying-us-bonds-2.qmd#美债利率和收益率)]其实成了债券市场的一个基准利率。

同样的道理，美国国债的收益率，由于其美元世界货币特性和美债市场的流动性，成为了世界的基准收益率。

如果一项资产的收益率不能高于美债提供的基础收益率，那为什么要去选择收益率低，安全性还不能和国家信用媲美的资产呢？相反，美债收益率如果下跌，逐利的资本自然要流向其他资产，甚至流出美国，如果大量美元流出美国，美国国内的资产价格就会下跌，造成严重的资产贬值和更大恐慌，这也是为什么特朗普在面对美债出现负面信号的时候，策略大反转的原因。

美债的收益率，事实上，就成了（世界范围内）资产定价的基准（锚）。



# 意义

前面涉及的都是国家，企业之间的逻辑，对我（们）普通人有什么意义呢？

之所以普通，是因为面对的这些历史事实和现实，是无法改变的。只能接受它，了解背后的逻辑和现实，才能更好的适应这个世界游戏。

当美债收益率高的时候，就是获得Free Money的机会。也是为什么美债收益率被称作无风险收益率^[无风险收益率：严格来讲，任何东西都有风险]的原因。


就像前面提到的，世界游戏的基本规则，学校不教，也不会教。我们都是被动的参与到这个游戏中来，熟悉游戏规则也成为了不得不做的事情。


{{< include ../include/telegram_channel.qmd >}}

