---
title: "深圳失业保险金线上申请过程"
date: "2026-01-07 13:31"
categories: ['first-time']
---


# 整体流程

1. 公司替你办理社保减员，并且原因是公司主动减员，办理成功后有短信通知。^[例如，我的是:【深圳社保局】，****有限公司于2025年12月31日为您办理停保，停保原因为[劳动合同期满（单位不续订）]，如停保原因与真实情况不符，请尽快联系用人单位重新申报。]
2. 进行失业登记，等待审核通过。
3. 申请领取失业保险金，并上传相关材料，等待审核通过。

上述步骤需要依次按照顺序进行。

# 具体步骤

**失业登记**

支付宝搜索「失业登记」，按照要求填写上面的信息，是否有失业保险金申领意愿一项确认选择「是」

2025-12-31日晚上申请，2026-01-04审核通过。

**失业金申领**

上一步提交资料后，下方有「申领失业保险待遇」的超链接，点进去填写相应资料，[附件处一定要上传]{.mark}

- 失业登记审核通过证明（手机截图）
- 身份证正反面
- 离职证明

2026-01-05申请^[第三次申请，前两次申请失败的经验在下面]，01-06初审通过，等待复审



# 实践经验

**社保减员后，失业登记和失业金申领是否可以同步申请？**

不行。两者审核是分开的，如果失业金申领审核时，而失业登记还未出结果，则失业金申请会直接不通过，理由是「不符合申请条件」

**通过支付宝申请失业金，附件不是必填项，是否可以不上传附件？**

不行。不上传附件会导致审核不通过，理由是「未上传材料，不满足办理条件」并且会给出上传材料的具体路径：

> 请通过【“深圳社保”微信公众号→ 掌上办→ 业务办理→ 失业业 失业保险金申请】上传身份证正反面、广东省内失业登记证明、用人单位出具的终止或解除劳动关系材料提交申请。 您可通过【深圳社保微信公众号-个人业务办理-业务跟踪查询-业务进度查询（转移及三险待遇业务）】查询。如有疑问，可拨打12333咨询。


**按照上面的短信内容指引，微信公众号上上传材料那一步一直超时^[就像[这种情况](https://x.com/luozxdotorg/status/2008138738933883064?s=20)]怎么办？**

换用支付宝进行申请并上传附件。两者是互斥的，当你在支付宝提交的时候，微信公众号上是能识别有正在待审的流程，拒绝你再次申请。


