---
title: "在日本读语言学校一个月要花多少钱"
date: "2026-07-06 15:26"
categories: ['tome-of-xp']
---

总体的费用可以分为固定支出和弹性支出两个部分，计价货币均为日元（JPY）。

固定支出是一些不可避免或者浮动范围不大的支出，比如房租，话费等。弹性支出属于数据差异可能很大的项目，还有一些甚至可以省略的项目，但是我还是尽量以自己的真实情况做说明，做一个有意义的统计数据点（Data Point）。

# 固定支出

## 房租

我租的房子是UR团地，房租56600，管理费4800。关于UR团地介绍和更多内容，可以在播客节目中更详细了解。（我也是这样了解到的）。

语言学校提供的宿舍（日语中叫做寮）和国内大学的宿舍不同，语言学校的宿舍和学校本身是合作关系，实际管理者并不是语言学校本身，而是和学校签订合同的各个房产公司。因此尽管叫做宿舍，但实际在物理位置上和普通的市售楼并无差别，会分散在学校周边，而不是传统上集中在一个区域，宿舍内住的人也不全是在语校上课学生，而是任何社会人。在价格上，学校推荐的宿舍也会根据实际楼房的不同，涵盖从三四万到七八万甚至十万以上的房源供学生选择。

之所以没有在学校宿舍中选择是因为在对比了UR团地提供的房屋信息后，相同价格的房子，面积会有一倍多的差别。当然团地也有很多缺点，先不展开了。

**电费**

| 每月电费 (JPY) | 统计天数| 使用电量 (千瓦时/度) | 每度电价格 (JPY/度) |
| :--- | :--- | :--- |:--- |
| 1177 | 30   | 36 | 32.6944444444 |
| 1390 | 31   | 44 | 31.5909090909 |
| 736  | 28   | 20 | 36.8 |

日均电费约为$\frac{1177 + 1390 + 736}{30 + 31 + 28}=\frac{3303}{89} \approx 37.1124$ JPY

每个月大约需要电费 $30\times37.1124=1113.37$ JPY


**燃气**

| 每月燃气费 (JPY) |统计天数| 使用气量 (立方米) | 每立方米燃气价格 (JPY/立方米) |
| :--- | :--- | :--- |:--- |
| 1609 | 28 | 5 | 321.8 |
| 2261 | 34| 13 | 173.9230769231 |
| 335 | 6 |2 | 167.5 |

日均燃气费约为$\frac{4205 \text{ JPY}}{68 \text{ 天}} \approx 61.8382 \text{ JPY/天}$

每个月大约需要燃气费$30\times61.8382\approx 1855.15$ JPY


**水费**

| 每月水费 (JPY) | 统计天数 | 使用水量 (立方米) | 每立方米水价格 (JPY/立方米) |
| :--- | :--- | :--- | :--- |
| 1573 | 28 | 3 | 524.3333333333 |
| 1595 | 31 | 5 | 319 |
| 1573 | 18 | 3 | 524.3333333333 |

日均水费约为$\frac{4741 \text{ JPY}}{77 \text{ 天}} \approx 61.5714 \text{ JPY/天}$

每个月大约需要水费$30\times615714\approx1847.14$JPY

每个月在住房上的开支为^[水电燃气的计费规则没有仔细去了解，就以实际支出做了大致的统计。]

| 房租 | 管理费 | 预估电费 | 预估燃气费 | 预估水费 | 月总开销合计 |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 56600 | 4800 | 1113.37 | 1855.15 | 1847.14 | **66215.66** |


## 保险
必要缴纳的保险只有国民保险（医保），并且学生可以做减免，我减免后大约2780JPY一个月^[具体金额可能和你所在的城市有所不同。]。

## 通讯

通讯包含每个月的手机话费和宽带费。除了每个月的套餐费用外，在第一次申办的时候通常还有开卡费等手续费。同样，为了计算每个月还是取平均值计算：

::: {#tbl-panel layout-ncol=2}

| 数据 | 金额 |
| :--- | :--- |
| 1 | 7639 |
| 2 | 4813 |
| 3 | 2731 |
| 4 | 2731 |

: 手机话费 {#tbl-mobilefee}

| 数据 | 金额 |
| :--- | :--- |
| 1 | 7144 |
| 2 | 4271 |
| 3 | 4271 |

: 宽带费 {#tbl-internetfee}

通讯费明细
:::

平均话费每个月为4478.50 JPY，平均宽带费为每个月5228.67JPY，每个月的通讯费约为：

|话费|宽带费|总金额|
|:--|:--|:--
|4478.50|5228.67|**9707.17**|

宽带我没有选传统的光纤宽带，一方面开通需要工作人员上门开通，要一笔约几万日元的费用。另一方面还要等至少一个月才能上门开通。最后就选择当天开通就可用的一个[随身Wi-Fi](http://xhslink.com/o/7ZdQu86QXeq)

每个月的固定支出约为：

|房屋|保险|通讯|固定开支|
|--|--|--|--|
|66215.66|2780|9707.17|**78702.83**|

# 弹性支出

## 通勤

日本的地铁/电车很贵，估摸着价格可能和深圳地铁11号线的商务车厢^[价格为普通车厢的3倍]接近，甚至更高。

只计算学校往返通勤的话，我一天需要480JPY，一个月按照22天，每个月的通讯费约为$480\times22=10560$ JPY

## 健身房

和话费一样，新报名的话会有一笔入会费，初期价格会高一些，有些还有设施维护费（据说每年只收一次）。而且我加入的这家fitplace24，喝水还要每个月收1100日元...

实际账单如下：

|数据|金额|类别|
|--|--|--|
|1|10740|新入会|
|2|4378|月费|
|3|4378|月费|
|4|5500|设施维护费|

平均每月按照5000计算好了。


# 合计

::: {.list-table}
- - []{colspan=2} 类别
  - 金额（JPY）

- - []{rowspan=3} 固定支出
  - 房屋水电燃气
  - 66215.66

- - 保险
  - 2780

- - 通讯
  - 9707.17

- - []{rowspan=2} 弹性支出
  - 通勤
  - 10560

- - 健身房
  - 5000

- - []{rowspan=2} 总金额
  - 
  - 94,262.83

:::

上面的统计并没有涵盖饮食的内容，把健身房的费用替换为饮食的话，在大阪读语校，每个月的支出可能至少需要十万日元左右。
